force-app/main/default/objects/Warranty__c/Warranty__c.object-meta.xml
<CustomObject>
    <label>Warranty</label>
    <nameField>
        <label>Warranty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warranties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warranty__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <description>Related assests</description>
    <inlineHelpText
  >Limited Warranty covers for a year and Extended Warranty covers for 2 years.</inlineHelpText>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Warranties</relationshipLabel>
    <relationshipName>Warranties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warranty__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when coverage ends</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Warranty__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when warranty coverage starts</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Warranty__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Two types of warranties offered</description>
    <inlineHelpText
  >Limited Warranty covers for a year and Extended Warranty covers for 2 years.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Limited</fullName>
                <default>true</default>
                <label>Limited</label>
            </value>
            <value>
                <fullName>Extended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/main/selector/WarrantiesSelector.cls
public class WarrantiesSelector extends fflib_SObjectSelector implements IWarrantiesSelector {
    
    public static IWarrantiesSelector newInstance() {
        return (IWarrantiesSelector) Application.Selector.newInstance(Warranty__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Warranty__c.Id,
            Warranty__c.Name,
            Warranty__c.Asset__c,
            Warranty__c.End_Date__c,
            Warranty__c.Start_Date__c,
            Warranty__c.Type__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Warranty__c.SObjectType;
    }

    public List<Warranty__c> selectAll() {
        return (List<Warranty__c>) Database.query(newQueryFactory().toSOQL());
    }

}