force-app/main/default/objects/Case/fields/Date_Due__c.field-meta.xml
<CustomField>
    <fullName>Date_Due__c</fullName>
    <label>Date Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_Reported__c.field-meta.xml
<CustomField>
    <fullName>Date_Reported__c</fullName>
    <label>Date Reported</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>Maintenance_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment_Maintenance_Item__c/Equipment_Maintenance_Item__c.object-meta.xml
<CustomObject>
    <label>Equipment Maintenance Item</label>
    <nameField>
        <displayFormat>PART-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Maintenance Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Maintenance_Item__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No spare parts meet this description or name.</errorMessage>
        <filterItems>
            <field>Product2.Replacement_Part__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Equipment Maintenance Items</relationshipLabel>
    <relationshipName>Equipment_Maintenance_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment_Maintenance_Item__c/fields/Maintenance_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Cycle__c</fullName>
    <formula>Equipment__r.Maintenance_Cycle__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Maintenance Cycle (Days)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment_Maintenance_Item__c/fields/Maintenance_Request__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Request__c</fullName>
    <label>Maintenance Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipment Maintenance Items</relationshipLabel>
    <relationshipName>Equipment_Maintenance_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Current_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Current_Inventory__c</fullName>
    <label>Current Inventory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Lifespan_Months__c.field-meta.xml
<CustomField>
    <fullName>Lifespan_Months__c</fullName>
    <label>Lifespan Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Maintenance_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Cycle__c</fullName>
    <description
  >Number of days required before routine maintenance is needed</description>
    <label>Maintenance Cycle (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Replacement_Part__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Part__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Replacement Part</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Warehouse_SKU__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_SKU__c</fullName>
    <externalId>true</externalId>
    <label>Warehouse SKU</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/main/test/TEST_Cases.cls
@isTest
private class TEST_Cases {
  @isTest
  static void testRoutineMaintenance() {
    ATK.SaveResult vehicleResults = ATK.prepare(Vehicle__c.SObjectType, 1)
      .field(Vehicle__c.Name)
      .index('Freebird')
      .save();

    ATK.SaveResult productResults = ATK.prepare(Product2.SObjectType, 2)
      .field(Product2.Name)
      .repeat('Tire', 'Motor')
      .field(Product2.Cost__c)
      .repeat(100)
      .field(Product2.Current_Inventory__c)
      .repeat(1)
      .field(Product2.Lifespan_Months__c)
      .repeat(1)
      .field(Product2.Maintenance_Cycle__c)
      .repeat(30)
      .field(Product2.Warehouse_SKU__c)
      .index('12XU')
      .field(Product2.IsActive)
      .repeat(true)
      .field(Product2.Replacement_Part__c)
      .repeat(true)
      .save();

    Vehicle__c thisVehcle = (Vehicle__c) vehicleResults.get(
        Vehicle__c.SObjectType,
        0
      )
      .get(0);
    Product2 thisProductTire = (Product2) productResults.get(
        Product2.SObjectType
      )
      .get(0);
    Product2 thisProductMotor = (Product2) productResults.get(
        Product2.SObjectType
      )
      .get(0);

    ATK.SaveResult caseResults = ATK.prepare(Case.SObjectType, 1)
      .field(Case.Subject)
      .index(thisVehcle.Name)
      .field(Case.Vehicle__c)
      .repeat(thisVehcle.Id)
      .field(Case.Status)
      .repeat('Open')
      .field(Case.Type)
      .repeat('Routine Maintenance')
      .field(Case.Date_Reported__c)
      .repeat(System.today())
      .save();

    Case thisCase = (Case) caseResults.get(Case.SObjectType, 0).get(0);

    // Use ATK.prepare@isTest private class  to set up test data for Equipment_Maintenance_Item__c
    ATK.prepare(Equipment_Maintenance_Item__c.SObjectType, 2)
      .field(Equipment_Maintenance_Item__c.Equipment__c)
      .repeat(thisProductTire.Id, thisProductMotor.Id)
      .field(Equipment_Maintenance_Item__c.Maintenance_Request__c)
      .repeat(thisCase.Id)
      .save();

    // Update the case status
    thisCase.Status = 'Closed';
    update thisCase;

    List<Case> newMaintRequestList = [
      SELECT Id
      FROM Case
      WHERE
        Type = 'Routine Maintenance'
        AND Status != 'Closed'
        AND Vehicle__c = :thisVehcle.Id
    ];

    System.assertEquals(
      2,
      [
          SELECT Id, Equipment__c
          FROM Equipment_Maintenance_Item__c
          WHERE Maintenance_Request__c = :newMaintRequestList.get(0).Id
        ]
        .size()
    );
  }
  @isTest
  static void testInspection() {
    fflib_ISObjectUnitOfWork theUnitOfWork = Application.UnitOfWork.newInstance();

    ATK.SaveResult vehicleResults = ATK.prepare(Vehicle__c.SObjectType, 1)
      .field(Vehicle__c.Name)
      .index('Freebird')
      .save();

    Vehicle__c thisVehicle = (Vehicle__c) vehicleResults.get(
        Vehicle__c.SObjectType,
        0
      )
      .get(0);

    ATK.SaveResult productSaveResult = ATK.prepare(Product2.SObjectType, 1)
      .field(Product2.Name)
      .index('Tires')
      .field(Product2.Cost__c)
      .repeat(100)
      .field(Product2.Current_Inventory__c)
      .repeat(1)
      .field(Product2.Lifespan_Months__c)
      .repeat(1)
      .field(Product2.Maintenance_Cycle__c)
      .repeat(30)
      .field(Product2.Warehouse_SKU__c)
      .index('12XU')
      .field(Product2.IsActive)
      .repeat(true)
      .save();

    Product2 thisProductTire = (Product2) productSaveResult.get(
        Product2.SObjectType,
        0
      )
      .get(0);

    ATK.SaveResult caseResults = ATK.prepare(Case.SObjectType, 1)
      .field(Case.Subject)
      .index(thisVehicle.Name)
      .field(Case.Vehicle__c)
      .repeat(thisVehicle.Id)
      .field(Case.Status)
      .repeat('Open')
      .field(Case.Type)
      .repeat('Inspection')
      .field(Case.Date_Reported__c)
      .repeat(System.today())
      .save();

    Case thisCase = (Case) caseResults.get(Case.SObjectType, 0).get(0);

    thisCase.Status = 'Closed';
    theUnitOfWork.registerDirty(thisCase);
    theUnitOfWork.commitWork();

    System.assertEquals(
      1,
      [
          SELECT ID
          FROM Case
          WHERE subject LIKE '%Freebird%' AND Status = 'Closed'
        ]
        .size()
    );
    System.assertEquals(
      0,
      [
          SELECT ID
          FROM Case
          WHERE
            Type = 'Routine Maintenance'
            AND Status != 'Closed'
            AND Vehicle__c = :thisVehicle.Id
        ]
        .size()
    );
  }
  @isTest
  static void testDate() {
    fflib_ISObjectUnitOfWork theUnitOfWork = Application.UnitOfWork.newInstance();
    ATK.SaveResult vehicleResults = ATK.prepare(Vehicle__c.SObjectType, 1)
      .field(Vehicle__c.Name)
      .index('Freebird')
      .save();

    // Retrieve the inserted vehicle using ATK.SaveResult
    Vehicle__c thisVehicle = (Vehicle__c) vehicleResults.get(
        vehicle__c.SObjectType,
        0
      )
      .get(0);

    ATK.SaveResult productResults = ATK.prepare(Product2.SObjectType, 1)
      .field(Product2.Name)
      .index('Tires')
      .field(Product2.Cost__c)
      .repeat(100)
      .field(Product2.Current_Inventory__c)
      .repeat(1)
      .field(Product2.Lifespan_Months__c)
      .repeat(1)
      .field(Product2.Maintenance_Cycle__c)
      .repeat(30)
      .field(Product2.Warehouse_SKU__c)
      .index('12XU')
      .field(Product2.IsActive)
      .repeat(true)
      .field(Product2.Replacement_Part__c)
      .repeat(true)
      .save();

    Product2 thisProductTires = (Product2) productResults.get(
        Product2.SObjectType,
        0
      )
      .get(0);

    ATK.SaveResult productMotorResults = ATK.prepare(Product2.SObjectType, 1)
      .field(Product2.Name)
      .index('Motor')
      .field(Product2.Cost__c)
      .repeat(100)
      .field(Product2.Current_Inventory__c)
      .repeat(1)
      .field(Product2.Lifespan_Months__c)
      .repeat(1)
      .field(Product2.Maintenance_Cycle__c)
      .repeat(15)
      .field(Product2.Warehouse_SKU__c)
      .repeat('13XU')
      .field(Product2.IsActive)
      .repeat(true)
      .field(Product2.Replacement_Part__c)
      .repeat(true)
      .save();

    Product2 thisProductMotor = (Product2) productMotorResults.get(
        Product2.SObjectType,
        0
      )
      .get(0);

    ATK.SaveResult caseResults = ATK.prepare(Case.SObjectType, 1)
      .field(Case.Subject)
      .index(thisVehicle.Name)
      .field(Case.Vehicle__c)
      .repeat(thisVehicle.Id)
      .field(Case.Status)
      .repeat('Open')
      .field(Case.Type)
      .repeat('Routine Maintenance')
      .field(Case.Date_Reported__c)
      .repeat(System.today())
      .save();

    Case thisCase = (Case) caseResults.get(Case.SObjectType, 0).get(0);

    ATK.SaveResult equipmentMaintenanceItemResults = ATK.prepare(
        Equipment_Maintenance_Item__c.SObjectType,
        2
      )
      .field(Equipment_Maintenance_Item__c.Equipment__c)
      .repeat(
        String.valueOf(thisProductTires.Id),
        String.valueOf(thisProductMotor.Id)
      )
      .field(Equipment_Maintenance_Item__c.Maintenance_Request__c)
      .repeat(thisCase.Id)
      .save();

    thisCase.Status = 'Closed';
    theUnitOfWork.registerDirty(thisCase);
    theUnitOfWork.commitWork();

    System.assertEquals(
      Date.Today().addDays(15),
      [
        SELECT Id, Date_Due__c
        FROM Case
        WHERE
          Type = 'Routine Maintenance'
          AND Status != 'Closed'
          AND Vehicle__c = :thisVehicle.Id
      ][0]
      .Date_Due__c
    );
  }
  @isTest
  static void testBulkAnotherCaseUpdate() {
    fflib_ISObjectUnitOfWork theUnitOfWork = Application.UnitOfWork.newInstance();
    ATK.SaveResult vehicleResults = ATK.prepare(Vehicle__c.SObjectType, 1)
      .field(Vehicle__c.Name)
      .index('Freebird')
      .save();

    // Retrieve the inserted vehicle using ATK.SaveResult
    Vehicle__c thisVehicle = (Vehicle__c) vehicleResults.get(
        vehicle__c.SObjectType,
        0
      )
      .get(0);

    ATK.SaveResult productResults = ATK.prepare(Product2.SObjectType, 1)
      .field(Product2.Name)
      .index('Tires')
      .field(Product2.Cost__c)
      .repeat(100)
      .field(Product2.Current_Inventory__c)
      .repeat(1)
      .field(Product2.Lifespan_Months__c)
      .repeat(1)
      .field(Product2.Maintenance_Cycle__c)
      .repeat(30)
      .field(Product2.Warehouse_SKU__c)
      .index('12XU')
      .field(Product2.IsActive)
      .repeat(true)
      .field(Product2.Replacement_Part__c)
      .repeat(true)
      .save();

    Product2 thisProductTires = (Product2) productResults.get(
        Product2.SObjectType,
        0
      )
      .get(0);

    ATK.SaveResult caseResults = ATK.prepare(Case.SObjectType, 201)
      .field(Case.Subject)
      .index(thisVehicle.Name)
      .field(Case.Vehicle__c)
      .repeat(thisVehicle.ID)
      .field(Case.Status)
      .repeat('New')
      .field(Case.Type)
      .repeat('Routine Maintenance', 'Repair')
      .field(Case.Date_Reported__c)
      .repeat(System.today())
      .withChildren(
        Equipment_Maintenance_Item__c.SObjectType,
        Equipment_Maintenance_Item__c.Maintenance_Request__c,
        1
      )
      .field(Equipment_Maintenance_Item__c.Equipment__c)
      .repeat(thisProductTires.ID)
      .save();

    // update all of the work orders as closed -- should create 200 more
    for (Case thisCase : (List<Case>) caseResults.get(Case.SObjectType, 0)) {
      thisCase.Status = 'Closed';
      theUnitOfWork.registerDirty(thisCase);
    }
    theUnitOfWork.commitWork();

    System.assertEquals(
      401,
      [SELECT COUNT() FROM Case WHERE Vehicle__c = :thisVehicle.Id]
    );
  }
}