force-app/main/default/objects/Case/fields/Date_Due__c.field-meta.xml
<CustomField>
    <fullName>Date_Due__c</fullName>
    <label>Date Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_Reported__c.field-meta.xml
<CustomField>
    <fullName>Date_Reported__c</fullName>
    <label>Date Reported</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/EngineeringReqNumber__c.field-meta.xml
<CustomField>
    <fullName>EngineeringReqNumber__c</fullName>
    <label>Engineering Req Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GC1040</fullName>
            </value>
            <value>
                <fullName>GC1060</fullName>
            </value>
            <value>
                <fullName>GC3020</fullName>
            </value>
            <value>
                <fullName>GC3040</fullName>
            </value>
            <value>
                <fullName>GC3060</fullName>
            </value>
            <value>
                <fullName>GC5020</fullName>
            </value>
            <value>
                <fullName>GC5040</fullName>
            </value>
            <value>
                <fullName>GC5060</fullName>
            </value>
            <value>
                <fullName>GC1020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SLAViolation__c.field-meta.xml
<CustomField>
    <fullName>SLAViolation__c</fullName>
    <label>SLA Violation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/main/selector/CasesSelector.cls
public class CasesSelector extends fflib_SObjectSelector implements ICasesSelector {
  public static ICasesSelector newInstance() {
    return (ICasesSelector) Application.Selector.newInstance(Case.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Case.Id,
      Case.AccountId,
      Case.CaseNumber,
      Case.Description,
      Case.Origin,
      Case.Reason,
      Case.ContactId,
      Case.Date_Due__c,
      Case.Date_Reported__c,
      Case.EngineeringReqNumber__c,
      Case.Priority,
      Case.Product__c,
      Case.ProductId,
      Case.SLAViolation__c,
      Case.Vehicle__c,
      Case.Status,
      Case.Type,
      Case.IsClosed
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Case.SObjectType;
  }

  public List<Case> selectAll() {
    return (List<Case>) Database.query(newQueryFactory().toSOQL());
  }

  public List<Case> selectWithMaintenanceRequestsAndProducts(
    Set<ID> caseIDSet
  ) {
    EquipmentMaintenanceItemsSelector theEquipmentMaintenanceItemsSelector = new EquipmentMaintenanceItemsSelector();
    fflib_QueryFactory caseQueryFactory = newQueryFactory();
    theEquipmentMaintenanceItemsSelector.addQueryFactorySubselect(
      caseQueryFactory
    );
    caseQueryFactory.setCondition('Id in: caseIDSet');

    return (List<Case>) Database.query(caseQueryFactory.toSOQL());
  }

  public Database.QueryLocator queryLocatorSelectAll() {
    return Database.getQueryLocator(newQueryFactory().toSOQL());
  }
}