force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Stores error details during a batch Apex job</description>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Async_Apex_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Async_Apex_Job_Id__c</fullName>
    <description>Apex Job Id</description>
    <inlineHelpText>Apex Job Id</inlineHelpText>
    <label>Async Apex Job Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Exception Message</description>
    <inlineHelpText>Exception Message</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <description>Exception Stacktrace</description>
    <inlineHelpText>Exception Stacktrace</inlineHelpText>
    <label>Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/main/domain/BatchApexErrorEvents.cls
public class BatchApexErrorEvents extends fflib_SObjects implements IBatchApexErrorEvents {
  public static IBatchApexErrorEvents newInstance(
    List<BatchApexErrorEvent> recordList
  ) {
    return (IBatchApexErrorEvents) Application.Domain.newInstance(recordList);
  }

  public static IBatchApexErrorEvents newInstance(Set<Id> recordIdSet) {
    return (IBatchApexErrorEvents) Application.Domain.newInstance(recordIdSet);
  }

  public BatchApexErrorEvents(List<BatchApexErrorEvent> sObjectList) {
    super(sObjectList, Schema.BatchApexErrorEvent.SObjectType);
  }

  public List<BatchApexErrorEvent> getBatchApexErrorEvents() {
    return (List<BatchApexErrorEvent>) getRecords();
  }

  public Map<ID, BatchApexErrorEvent> getBatchApexErrorEventsMap() {
    return new Map<ID, BatchApexErrorEvent>(getBatchApexErrorEvents());
  }

  public void processBatchApexErrorEvents(
    fflib_ISObjectUnitOfWork theUnitOfWork
  ) {
    for (BatchApexErrorEvent errorEvent : getBatchApexErrorEvents()) {
      Error_Log__c errorLog = new Error_Log__c();
      errorLog.Message__c = errorEvent.Message;
      errorLog.StackTrace__c = errorEvent.StackTrace;
      errorLog.Async_Apex_Job_Id__c = errorEvent.AsyncApexJobId;
      theUnitOfWork.registerNew(errorLog);
    }
  }

  public class Constructor implements fflib_IDomainConstructor {
    public fflib_SObjects construct(List<Object> objectList) {
      return new BatchApexErrorEvents((List<SObject>) objectList);
    }
  }
}