force-app/main/default/objects/Mission__c/Mission__c.object-meta.xml
<CustomObject>
    <description
  >A job opportunity for a drone pilot interested in contracting.</description>
    <label>Mission</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Mission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mission__c/fields/Completion_Rating__c.field-meta.xml
<CustomField>
    <fullName>Completion_Rating__c</fullName>
    <description>Rate at completion</description>
    <inlineHelpText>Rate at completion</inlineHelpText>
    <label>Completion Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mission__c/fields/Overall_Rating__c.field-meta.xml
<CustomField>
    <fullName>Overall_Rating__c</fullName>
    <description>Overall Rating</description>
    <inlineHelpText>Overall Rating</inlineHelpText>
    <label>Overall Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mission__c/fields/Pilot__c.field-meta.xml
<CustomField>
    <fullName>Pilot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact who picks up the project.</description>
    <inlineHelpText>Contact who picks up the project.</inlineHelpText>
    <label>Pilot</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mission</relationshipLabel>
    <relationshipName>Mission</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mission__c/fields/Safety_Incidents__c.field-meta.xml
<CustomField>
    <fullName>Safety_Incidents__c</fullName>
    <description>Number of safety incidents</description>
    <inlineHelpText>Number of safety incidents</inlineHelpText>
    <label>Safety Incidents</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mission__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Title of the project</description>
    <inlineHelpText>Title of the project</inlineHelpText>
    <label>Subject</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/main/test/TEST_Missions.cls
@IsTest
private class TEST_Missions implements Database.RaisesPlatformEvents {
  @TestSetup
  static void makeData() {
    ATK.SaveResult pilotContactResult = ATK.prepare(Contact.SObjectType, 5)
      .field(Contact.FirstName)
      .index('FirstName-{0000}')
      .field(Contact.LastName)
      .index('LastName-{0000}')
      .withChildren(Mission__c.SObjectType, Mission__c.Pilot__c, 5)
      .field(Mission__c.Completion_Rating__c)
      .repeat(4.5)
      .field(Mission__c.Overall_Rating__c)
      .repeat(3.2)
      .field(Mission__c.Safety_Incidents__c)
      .repeat(2)
      .field(Mission__c.Subject__c)
      .index('Subject-{0000}')
      .save();
    ATK.SaveResult pilotlessMissionResult = ATK.prepare(
        Mission__c.SObjectType,
        5
      )
      .field(Mission__c.Completion_Rating__c)
      .repeat(4.5)
      .field(Mission__c.Overall_Rating__c)
      .repeat(3.2)
      .field(Mission__c.Safety_Incidents__c)
      .repeat(2)
      .field(Mission__c.Subject__c)
      .index('Subject-{0000}')
      .save();
  }

  @IsTest
  static void testPublishBatchApexErrorEvent() {
    // Start the batch
    Test.startTest();
    PilotRatingBatch batch = new PilotRatingBatch();
    Database.executeBatch(batch);
    Test.stopTest();
  }
}