force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Certification for aircraft</description>
    <label>Certification</label>
    <nameField>
        <label>Certification  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Certification_Number__c.field-meta.xml
<CustomField>
    <fullName>Certification_Number__c</fullName>
    <description>Issued number for certification</description>
    <displayFormat>LP{000000}</displayFormat>
    <label>Certification Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is the certification Active?</description>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/main/selector/CertificationsSelector.cls
public class CertificationsSelector extends fflib_SObjectSelector implements ICertificationsSelector {
  public static ICertificationsSelector newInstance() {
    return (ICertificationsSelector) Application.Selector.newInstance(
      Certification__c.SObjectType
    );
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Certification__c.Id,
      Certification__c.Name,
      Certification__c.Certification_Number__c,
      Certification__c.isActive__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Certification__c.SObjectType;
  }
}