force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Certification for aircraft</description>
    <label>Certification</label>
    <nameField>
        <label>Certification  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is the certification Active?</description>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/Contact_Certification__c.object-meta.xml
<CustomObject>
    <description>Junction object between Contact and Certification</description>
    <label>Contact Certification</label>
    <nameField>
        <displayFormat>M{000000000}</displayFormat>
        <label>Contact Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Certification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <description>Certification related to the contact</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Contact Certifications</relationshipLabel>
    <relationshipName>Contact_Certifications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>contact for certification</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Certifications</relationshipLabel>
    <relationshipName>Contact_Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <description>Date of certification issue</description>
    <label>Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/main/selector/ContactCertificationsSelector.cls
public class ContactCertificationsSelector extends fflib_SObjectSelector implements IContactCertificationsSelector {
  public static IContactCertificationsSelector newInstance() {
    return (IContactCertificationsSelector) Application.Selector.newInstance(
      Contact_Certification__c.SObjectType
    );
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Contact_Certification__c.Id,
      Contact_Certification__c.Name,
      Contact_Certification__c.Certification__c,
      Contact_Certification__c.Contact__c,
      Contact_Certification__c.isActive__c,
      Contact_Certification__c.Issue_Date__c
    };
  }
  public Schema.SObjectType getSObjectType() {
    return Contact_Certification__c.SObjectType;
  }

  public List<Contact_Certification__c> selectByContactIDAndCertificationID(
    Set<Id> contactIDSet,
    Set<Id> certificationIDSet
  ) {
    fflib_QueryFactory contactCertificationQueryFactory = newQueryFactory();
    contactCertificationQueryFactory.setCondition(
      'Contact__c IN :contactIDSet AND Certification__c IN :certificationIDSet'
    );
    return Database.query(contactCertificationQueryFactory.toSOQL());
  }
  public List<Contact_Certification__c> selectByContactNameAndCertificationName(
    List<String> contactNameList,
    List<String> certifcationNameList
  ) {
    return Database.query(
      newQueryFactory()
        .selectField('Contact__r.LastName')
        .selectField('Certification__r.Name')
        .setCondition(
          'Contact__r.LastName IN :contactNameList AND Name IN :certifcationNameList'
        )
        .toSOQL()
    );
  }

  public List<Contact_Certification__c> selectAll() {
    return (List<Contact_Certification__c>) Database.query(
      newQueryFactory().toSOQL()
    );
  }
}