force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Certification for aircraft</description>
    <label>Certification</label>
    <nameField>
        <label>Certification  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Insurance claim filed by a customer</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C{0000000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/Contact_Certification__c.object-meta.xml
<CustomObject>
    <description>Junction object between Contact and Certification</description>
    <label>Contact Certification</label>
    <nameField>
        <displayFormat>M{000000000}</displayFormat>
        <label>Contact Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Certification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <description>Certification related to the contact</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Contact Certifications</relationshipLabel>
    <relationshipName>Contact_Certifications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipment_Maintenance_Item__c/Equipment_Maintenance_Item__c.object-meta.xml
<CustomObject>
    <label>Equipment Maintenance Item</label>
    <nameField>
        <displayFormat>PART-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Maintenance Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Stores error details during a batch Apex job</description>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <description>Insurance details for aircraft</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>IS{0000000}</displayFormat>
        <label>Policy ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mission__c/Mission__c.object-meta.xml
<CustomObject>
    <description
  >A job opportunity for a drone pilot interested in contracting.</description>
    <label>Mission</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Mission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Event__e/Order_Event__e.object-meta.xml
<CustomObject>
    <label>Order Event</label>
    <pluralLabel>Order Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Geo_Mapping__mdt/Product_Geo_Mapping__mdt.object-meta.xml
<CustomObject>
    <description
  >Metadata to map Products to the minimum permissible fly zones in different countries.</description>
    <label>Product Geo Mapping</label>
    <pluralLabel>Product Geo Mappings</pluralLabel>
</CustomObject>

force-app/main/default/classes/Application.cls
public class Application {
  // Configure and create the UnitOfWorkFactory for this Application
  public static final fflib_Application.UnitOfWorkFactory UnitOfWork = new fflib_Application.UnitOfWorkFactory(
    new List<SObjectType>{
      Lead.SObjectType,
      Account.SObjectType,
      Contact.SObjectType,
      Opportunity.SObjectType,
      Product2.SObjectType,
      Case.SObjectType,
      Asset.SObjectType,
      Insurance__c.SObjectType,
      Claim__c.SObjectType,
      Certification__C.SObjectType,
      Contact_Certification__c.SObjectType,
      Equipment_Maintenance_Item__c.SObjectType,
      Mission__c.SObjectType,
      PricebookEntry.SObjectType,
      Order.SObjectType,
      OrderItem.SObjectType,
      OpportunityLineItem.SObjectType,
      Wellness_Journey__c.SObjectType,
      Error_Log__c.SObjectType,
      Accessibility_Project__c.SObjectType,
      Task.SObjectType,
      Order_Event__e.SObjectType,
      BatchApexErrorEvent.SObjectType
    }
  );

  //   // Configure and create the ServiceFactory for this Application
  //   public static final fflib_Application.ServiceFactory Service = new fflib_Application.ServiceFactory(
  //     new Map<Type, Type>{
  //       IAccountsService.class => AccountsServiceImpl.class,
  //       IOpportunitiesService.class => OpportunitiesServiceImpl.class,
  //       IInvoicingService.class => InvoicingServiceImpl.class
  //     }
  //   );

  // Configure and create the SelectorFactory for this Application
  public static final fflib_Application.SelectorFactory Selector = new fflib_Application.SelectorFactory(
    new Map<SObjectType, Type>{
      Account.SObjectType => AccountsSelector.class,
      Contact.SObjectType => ContactsSelector.class,
      Opportunity.SObjectType => OpportunitiesSelector.class,
      Lead.SObjectType => LeadsSelector.class,
      Case.SObjectType => CasesSelector.class,
      Product2.SObjectType => ProductsSelector.class,
      PricebookEntry.SObjectType => PricebookEntriesSelector.class,
      Order.SObjectType => OrdersSelector.class,
      OrderItem.SObjectType => OrderitemsSelector.class,
      Asset.SObjectType => AssetsSelector.class,
      Insurance__c.SObjectType => InsurancesSelector.class,
      Claim__c.SObjectType => ClaimsSelector.class,
      Certification__C.SObjectType => ContactCertifications.class,
      Contact_Certification__c.SObjectType => ContactCertificationsSelector.class,
      Equipment_Maintenance_Item__c.SObjectType => EquipmentMaintenanceItemsSelector.class,
      Wellness_Journey__c.SObjectType => WellnessJourneysSelector.class,
      Accessibility_Project__c.SObjectType => AccessibilityProjectsSelector.class,
      Product_Geo_Mapping__mdt.SObjectType => ProductGeoMappingSelector.class
    }
  );

  // Configure and create the DomainFactory for this Application
  public static final fflib_Application.DomainFactory Domain = new fflib_Application.DomainFactory(
    Application.Selector,
    new Map<SObjectType, Type>{
      Lead.SObjectType => Leads.Constructor.class,
      Account.SObjectType => Accounts.Constructor.class,
      Contact.SObjectType => Contacts.Constructor.class,
      Opportunity.SObjectType => Opportunities.Constructor.class,
      Case.SObjectType => Cases.Constructor.class,
      Asset.SObjectType => Assets.Constructor.class,
      Product2.SObjectType => Products.Constructor.class,
      PricebookEntry.SObjectType => PricebookEntries.Constructor.class,
      Order.SObjectType => Orders.Constructor.class,
      OrderItem.SObjectType => Orderitems.Constructor.class,
      Insurance__c.SObjectType => Insurances.Constructor.class,
      Claim__c.SObjectType => Claims.Constructor.class,
      Certification__C.SObjectType => Certifications.Constructor.class,
      Contact_Certification__c.SObjectType => ContactCertifications.Constructor.class,
      Mission__c.SObjectType => Missions.Constructor.class,
      Product2.SObjectType => Products.Constructor.class,
      Order_Event__e.SObjectType => OrderEvents.Constructor.class,
      Wellness_Journey__c.SObjectType => WellnessJourneys.Constructor.class,
      Accessibility_Project__c.SObjectType => AccessibilityProjects.Constructor.class,
      BatchApexErrorEvent.SObjectType => BatchApexErrorEvents.Constructor.class
    }
  );
}