force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Certification for aircraft</description>
    <label>Certification</label>
    <nameField>
        <label>Certification  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is the certification Active?</description>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/Contact_Certification__c.object-meta.xml
<CustomObject>
    <description>Junction object between Contact and Certification</description>
    <label>Contact Certification</label>
    <nameField>
        <displayFormat>M{000000000}</displayFormat>
        <label>Contact Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Certification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <description>Certification related to the contact</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Contact Certifications</relationshipLabel>
    <relationshipName>Contact_Certifications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>contact for certification</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Certifications</relationshipLabel>
    <relationshipName>Contact_Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <description>Date of certification issue</description>
    <label>Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/main/test/TEST_Certifications.cls
@IsTest
private class TEST_Certifications {
  @TestSetup
  static void makeData() {
    ATK.SaveResult accountContactResult = ATK.prepare(Account.SObjectType, 5)
      .field(Account.Name)
      .index('Account-{0000}')
      .withChildren(Contact.SObjectType, Contact.AccountId, 5)
      .field(Contact.FirstName)
      .index('First-{0000}')
      .field(Contact.LastName)
      .index('Last-{0000}')
      .save();

    List<Id> accountIds = new List<Id>();
    List<Id> contactIds = new List<Id>();
    for (
      Contact con : (List<Contact>) accountContactResult.get(
        Contact.SObjectType,
        0
      )
    ) {
      contactIds.add(con.Id);
    }

    ATK.SaveResult certificationResult = ATK.prepare(
        Certification__c.SObjectType,
        5
      )
      .field(Certification__c.Name)
      .index('Certification-{0000}')
      .save();

    List<Id> certificationIds = new List<Id>();
    for (
      Certification__c cert : (List<Certification__c>) certificationResult.get(
        Certification__c.SObjectType,
        0
      )
    ) {
      certificationIds.add(cert.Id);
    }

    ATK.SaveResult contactCertificationResult = ATK.prepare(
        Contact_Certification__c.SObjectType,
        10
      )
      .field(Contact_Certification__c.Contact__c)
      .repeat(contactIds)
      .field(Contact_Certification__c.Certification__c)
      .repeat(certificationIds)
      .field(Contact_Certification__c.isActive__c)
      .repeat(true, false)
      .field(Contact_Certification__c.Issue_Date__c)
      .repeat(Date.today())
      .save();
  }

  @isTest
  static void testBadContactName() {
    String result = CredentialVerificationService.verifyCredential(
      'bad',
      [SELECT ID, Name FROM Contact_Certification__c LIMIT 1][0].Name
    );
    Assert.areEqual('No record found', result);
  }

  @isTest
  static void testBadCertificationName() {
    String result = CredentialVerificationService.verifyCredential(
      [SELECT ID, LastName FROM Contact LIMIT 1][0].LastName,
      'Bad'
    );
    Assert.areEqual('No record found', result);
  }

  @isTest
  static void testActiveCertification() {
    IContacts theseContacts = Contacts.newInstance(
      ContactsSelector.newInstance().selectAll()
    );
    IContactCertifications theseContactCertifications = ContactCertifications.newInstance(
      ContactCertificationsSelector.newInstance().selectAll()
    );

    String result = CredentialVerificationService.verifyCredential(
      theseContacts.getContactsMap()
        .get(
          theseContactCertifications.getContactCertifications()[0].Contact__c
        )
        .LastName,
      theseContactCertifications.getContactCertifications()[0].Name
    );
    Assert.areEqual('Valid', result);
  }

  @isTest
  static void testInActiveCertification() {
    IContacts theseContacts = Contacts.newInstance(
      ContactsSelector.newInstance().selectAll()
    );
    IContactCertifications theseContactCertifications = ContactCertifications.newInstance(
      ContactCertificationsSelector.newInstance().selectAll()
    );

    String result = CredentialVerificationService.verifyCredential(
      theseContacts.getContactsMap()
        .get(
          theseContactCertifications.getContactCertifications()[1].Contact__c
        )
        .LastName,
      theseContactCertifications.getContactCertifications()[1].Name
    );
    Assert.areEqual('Needs Renewal', result);
  }
}