force-app/main/default/objects/Accessibility_Project__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount allocated for the initiative.</description>
    <inlineHelpText>Amount allocated for the initiative.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Accessibility_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the project submission to the Billing Invoice Service.</description>
    <inlineHelpText>Status of the project submission to the Billing Invoice Service.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accessibility_Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Category of the initiative.</description>
    <inlineHelpText>Category of the initiative.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sign Language Interpreters</fullName>
            </value>
            <value>
                <fullName>Hearing Assistive Technology</fullName>
            </value>
            <value>
                <fullName>Accessibility Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/main/selector/AccessibilityProjectsSelector.cls
public class AccessibilityProjectsSelector extends fflib_SObjectSelector implements IAccessibilityProjectsSelector {
    
    public static IAccessibilityProjectsSelector newInstance() {
        return (IAccessibilityProjectsSelector) Application.Selector.newInstance(Accessibility_Project__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Accessibility_Project__c.Id,
            Accessibility_Project__c.Name,
            Accessibility_Project__c.Amount__c,
            Accessibility_Project__c.Status__c,
            Accessibility_Project__c.Type__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Accessibility_Project__c.SObjectType;
    }

    public List<Accessibility_Project__c> selectAll() {
        return (List<Accessibility_Project__c>) Database.query(newQueryFactory().toSOQL());
    }
}