force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Air_Conditioner__c.field-meta.xml
<CustomField>
    <fullName>Air_Conditioner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Air Conditioner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Awning__c.field-meta.xml
<CustomField>
    <fullName>Awning__c</fullName>
    <label>Awning</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Backup_Camera_Monitor__c.field-meta.xml
<CustomField>
    <fullName>Backup_Camera_Monitor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Backup Camera/Monitor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Bathroom_Hookup__c.field-meta.xml
<CustomField>
    <fullName>Bathroom_Hookup__c</fullName>
    <label>Bathroom Hookup</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Walk-In Shower</fullName>
            </value>
            <value>
                <fullName>Tub/Shower Combo</fullName>
            </value>
            <value>
                <fullName>No Shower</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Bathrooms__c.field-meta.xml
<CustomField>
    <fullName>Bathrooms__c</fullName>
    <label>Bathrooms</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Bedrooms__c.field-meta.xml
<CustomField>
    <fullName>Bedrooms__c</fullName>
    <label>Bedrooms</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Fancy_Sound_System__c.field-meta.xml
<CustomField>
    <fullName>Fancy_Sound_System__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fancy Sound System</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Levelers__c.field-meta.xml
<CustomField>
    <fullName>Levelers__c</fullName>
    <label>Levelers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/License_Plate__c.field-meta.xml
<CustomField>
    <fullName>License_Plate__c</fullName>
    <label>License Plate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Power__c.field-meta.xml
<CustomField>
    <fullName>Power__c</fullName>
    <label>Power</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diesel-Powered Class B</fullName>
            </value>
            <value>
                <fullName>Front-Engine Diesel</fullName>
            </value>
            <value>
                <fullName>Regular Diesel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Propane_Tank__c.field-meta.xml
<CustomField>
    <fullName>Propane_Tank__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Propane Tank</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Recommended_Passengers__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Passengers__c</fullName>
    <label>Recommended Passengers</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Roof_Mounted_Antenna__c.field-meta.xml
<CustomField>
    <fullName>Roof_Mounted_Antenna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Roof Mounted Antenna</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Shower__c.field-meta.xml
<CustomField>
    <fullName>Shower__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shower</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Tub__c.field-meta.xml
<CustomField>
    <fullName>Tub__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tub</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Luxury</fullName>
            </value>
            <value>
                <fullName>Mid-Range</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/VIN_Number__c.field-meta.xml
<CustomField>
    <fullName>VIN_Number__c</fullName>
    <label>VIN Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/main/selector/VehiclesSelector.cls
public class VehiclesSelector extends fflib_SObjectSelector implements IVehiclesSelector {
  public static IVehiclesSelector newInstance() {
    return (IVehiclesSelector) Application.Selector.newInstance(
      Vehicle__c.SObjectType
    );
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Vehicle__c.Id,
      Vehicle__c.Air_Conditioner__c,
      Vehicle__c.Awning__c,
      Vehicle__c.Backup_Camera_Monitor__c,
      Vehicle__c.Bathroom_Hookup__c,
      Vehicle__c.Bathrooms__c,
      Vehicle__c.Bedrooms__c,
      Vehicle__c.Fancy_Sound_System__c,
      Vehicle__c.Levelers__c,
      Vehicle__c.License_Plate__c,
      Vehicle__c.Make__c,
      Vehicle__c.Model__c,
      Vehicle__c.Power__c,
      Vehicle__c.Propane_Tank__c,
      Vehicle__c.Recommended_Passengers__c,
      Vehicle__c.Roof_Mounted_Antenna__c,
      Vehicle__c.Shower__c,
      Vehicle__c.Tub__c,
      Vehicle__c.Type__c,
      Vehicle__c.Name,
      Vehicle__c.VIN_Number__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Vehicle__c.SObjectType;
  }

  public List<Vehicle__c> selectAll() {
    return (List<Vehicle__c>) Database.query(newQueryFactory().toSOQL());
  }

  public Database.QueryLocator queryLocatorSelectAll() {
    return Database.getQueryLocator(newQueryFactory().toSOQL());
  }
}