force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <description>Insurance details for aircraft</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>IS{0000000}</displayFormat>
        <label>Policy ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Shows whether the policy is active or not</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Insurances</relationshipLabel>
    <relationshipName>Insurances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <description>Types of coverage available</description>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comprehensive</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Flyaway</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/main/selector/InsurancesSelector.cls
public class InsurancesSelector extends fflib_SObjectSelector implements IInsurancesSelector {
  public static IInsurancesSelector newInstance() {
    return (IInsurancesSelector) Application.Selector.newInstance(
      Insurance__c.SObjectType
    );
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Insurance__c.Id,
      Insurance__c.Name,
      Insurance__c.Active__c,
      Insurance__c.Asset__c,
      Insurance__c.Coverage__c,
      Insurance__c.End_Date__c,
      Insurance__c.Start_Date__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Insurance__c.SObjectType;
  }
}