force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <description>Insurance details for aircraft</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>IS{0000000}</displayFormat>
        <label>Policy ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Insurances</relationshipLabel>
    <relationshipName>Insurances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/main/domain/Assets.cls
public class Assets extends fflib_SObjects implements IAssets {
  public static IAssets newInstance(List<Asset> recordList) {
    return (IAssets) Application.Domain.newInstance(recordList);
  }

  public static IAssets newInstance(Set<Id> recordIdSet) {
    return (IAssets) Application.Domain.newInstance(recordIdSet);
  }

  public Assets(List<Asset> sObjectList) {
    super(sObjectList, Schema.Asset.SObjectType);
  }

  public List<Asset> getAssets() {
    return (List<Asset>) getRecords();
  }

  public Map<ID, Asset> getAssetsMap() {
    return new Map<ID, Asset>(getAssets());
  }

  public Map<ID, List<Insurance__c>> getAssetsInsurancesMap() {
    Map<ID, List<Insurance__c>> assetsInsurancesMap = new Map<ID, List<Insurance__c>>();
    for (Asset thisAsset : getAssets()) {
      for (Insurance__c thisInsurance : thisAsset.Insurances__r) {
        if (assetsInsurancesMap.get(thisAsset.ID) == null) {
          assetsInsurancesMap.put(
            thisAsset.ID,
            new List<Insurance__c>{ thisInsurance }
          );
        } else {
          assetsInsurancesMap.get(thisAsset.ID).add(thisInsurance);
        }
      }
    }
    return assetsInsurancesMap;
  }

  public class Constructor implements fflib_IDomainConstructor {
    public fflib_SObjects construct(List<Object> objectList) {
      return new Assets((List<SObject>) objectList);
    }
  }
}