force-app/main/default/objects/Product_Geo_Mapping__mdt/Product_Geo_Mapping__mdt.object-meta.xml
<CustomObject>
    <description
  >Metadata to map Products to the minimum permissible fly zones in different countries.</description>
    <label>Product Geo Mapping</label>
    <pluralLabel>Product Geo Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Geo_Mapping__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>ISO Aplpha-2 code for countries</description>
    <inlineHelpText>Alpha-2 country code</inlineHelpText>
    <label>Country Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Geo_Mapping__mdt/fields/Permissible_Fly_Zone__c.field-meta.xml
<CustomField>
    <fullName>Permissible_Fly_Zone__c</fullName>
    <description>allowed area&apos;s for specific air craft</description>
    <label>Permissible Fly Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recommended</fullName>
                <default>true</default>
                <label>Recommended</label>
            </value>
            <value>
                <fullName>Regulated</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Geo_Mapping__mdt/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/main/selector/ProductGeoMappingSelector.cls
public class ProductGeoMappingSelector extends fflib_SObjectSelector implements IProductGeoMappingSelector {
  public static IProductGeoMappingSelector newInstance() {
    return (IProductGeoMappingSelector) Application.Selector.newInstance(
      Product_Geo_Mapping__mdt.SObjectType
    );
  }

  public Schema.SObjectType getSObjectType() {
    return Product_Geo_Mapping__mdt.SObjectType;
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Product_Geo_Mapping__mdt.Id,
      Product_Geo_Mapping__mdt.MasterLabel,
      Product_Geo_Mapping__mdt.Country_Code__c,
      Product_Geo_Mapping__mdt.Permissible_Fly_Zone__c,
      Product_Geo_Mapping__mdt.Product_Family__c
    };
  }

  public List<Product_Geo_Mapping__mdt> selectByCountryAndProductFamily(
    List<String> countryCodeList,
    List<String> productFamilyList
  ) {
    fflib_QueryFactory queryFactory = newQueryFactory()
      .setCondition(
        'Country_Code__c IN :countryCodeList AND Product_Family__c IN :productFamilyList'
      );
    System.debug(queryFactory.toSOQL());
    return (List<Product_Geo_Mapping__mdt>) Database.query(
      queryFactory.toSOQL()
    );
  }
}