force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Insurance claim filed by a customer</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C{0000000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer filing the claim</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the insurance claim</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Damage</fullName>
            </value>
            <value>
                <fullName>Loss</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Injury</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <description>Insurance details for aircraft</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>IS{0000000}</displayFormat>
        <label>Policy ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Insurances</relationshipLabel>
    <relationshipName>Insurances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <description>Types of coverage available</description>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comprehensive</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Flyaway</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/main/selector/ClaimsSelector.cls
public class ClaimsSelector extends fflib_SObjectSelector implements IClaimsSelector {
  public static IClaimsSelector newInstance() {
    return (IClaimsSelector) Application.Selector.newInstance(
      Claim__c.SObjectType
    );
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Claim__c.Id,
      Claim__c.Name,
      Claim__c.Asset__c,
      Claim__c.Contact__c,
      Claim__c.Description__c,
      Claim__c.Insurance__c,
      Claim__c.Status__c,
      Claim__c.Type__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Claim__c.SObjectType;
  }

  public List<Claim__c> selectByNameWithComprehensiveInsurance(
    List<String> claimNamesList
  ) {
    return Database.query(
      newQueryFactory()
        .selectField('Insurance__r.Coverage__c')
        .setCondition('Name in :claimNamesList')
        .setCondition('Insurance__r.Coverage__c = \'Comprehensive\'')
        .toSOQL()
    );
  }

  public List<Claim__c> selectByAssetsWithInsuranceCoverage(
    List<String> assetIdsList
  ) {
    return Database.query(
      newQueryFactory()
        .selectField('Insurance__r.Coverage__c')
        .setCondition('Asset__c IN :assetIdsList')
        .setCondition('Insurance__r.Coverage__c = \'Comprehensive\'')
        .toSOQL()
    );
  }

  public List<Claim__c> selectWithInsuranceCoverage(List<String> assetIdsList) {
    return Database.query(
      newQueryFactory()
        .selectField('Insurance__r.Coverage__c')
        .setCondition('Asset__c IN :assetIdsList')
        .toSOQL()
    );
  }

  public List<Claim__c> selectAll() {
    return (List<Claim__c>) Database.query(newQueryFactory().toSOQL());
  }

  public List<Claim__c> selectWithAssetID(Set<ID> assetIdsSet) {
    return Database.query(
      newQueryFactory().setCondition('Asset__c IN :assetIdsSet').toSOQL()
    );
  }
}