force-app/main/default/objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Current_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Current_Inventory__c</fullName>
    <label>Current Inventory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Lifespan_Months__c.field-meta.xml
<CustomField>
    <fullName>Lifespan_Months__c</fullName>
    <label>Lifespan Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Maintenance_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Cycle__c</fullName>
    <description
  >Number of days required before routine maintenance is needed</description>
    <label>Maintenance Cycle (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Replacement_Part__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Part__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Replacement Part</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Warehouse_SKU__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_SKU__c</fullName>
    <externalId>true</externalId>
    <label>Warehouse SKU</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/main/selector/ProductsSelector.cls
public class ProductsSelector extends fflib_SObjectSelector implements IProductsSelector {
  public static ICasesSelector newInstance() {
    return (ICasesSelector) Application.Selector.newInstance(
      Product2.SObjectType
    );
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Product2.Id,
      Product2.IsActive,
      Product2.Cost__c,
      Product2.Current_Inventory__c,
      Product2.ProductCode,
      Product2.Name,
      Product2.Maintenance_Cycle__c,
      Product2.Lifespan_Months__c,
      Product2.Lifespan_Months__c,
      Product2.Replacement_Part__c,
      Product2.SourceProductId,
      Product2.Warehouse_SKU__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Product2.SObjectType;
  }

  public List<Product2> selectAll() {
    return (List<Product2>) Database.query(newQueryFactory().toSOQL());
  }
  public List<Product2> selectWithEquipmentMaintenanceItems(
    Set<ID> productIDSet
  ) {
    EquipmentMaintenanceItemsSelector thisEquipmentMaintenanceItemsSelector = new EquipmentMaintenanceItemsSelector();
    fflib_QueryFactory productQueryFactory = newQueryFactory();
    productQueryFactory.setCondition('id in: productIDSet');
    thisEquipmentMaintenanceItemsSelector.addQueryFactorySubselect(
      productQueryFactory
    );
    return Database.query(productQueryFactory.toSOQL());
  }
}