force-app/main/default/objects/Contact/fields/Pilot_Rating__c.field-meta.xml
<CustomField>
    <fullName>Pilot_Rating__c</fullName>
    <description>Overall Rating for the pilot</description>
    <inlineHelpText>Overall Rating for the pilot</inlineHelpText>
    <label>Pilot Rating</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Stores error details during a batch Apex job</description>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Async_Apex_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Async_Apex_Job_Id__c</fullName>
    <description>Apex Job Id</description>
    <inlineHelpText>Apex Job Id</inlineHelpText>
    <label>Async Apex Job Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Exception Message</description>
    <inlineHelpText>Exception Message</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <description>Exception Stacktrace</description>
    <inlineHelpText>Exception Stacktrace</inlineHelpText>
    <label>Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mission__c/Mission__c.object-meta.xml
<CustomObject>
    <description
  >A job opportunity for a drone pilot interested in contracting.</description>
    <label>Mission</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Mission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mission__c/fields/Completion_Rating__c.field-meta.xml
<CustomField>
    <fullName>Completion_Rating__c</fullName>
    <description>Rate at completion</description>
    <inlineHelpText>Rate at completion</inlineHelpText>
    <label>Completion Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mission__c/fields/Overall_Rating__c.field-meta.xml
<CustomField>
    <fullName>Overall_Rating__c</fullName>
    <description>Overall Rating</description>
    <inlineHelpText>Overall Rating</inlineHelpText>
    <label>Overall Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mission__c/fields/Pilot__c.field-meta.xml
<CustomField>
    <fullName>Pilot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact who picks up the project.</description>
    <inlineHelpText>Contact who picks up the project.</inlineHelpText>
    <label>Pilot</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mission</relationshipLabel>
    <relationshipName>Mission</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mission__c/fields/Safety_Incidents__c.field-meta.xml
<CustomField>
    <fullName>Safety_Incidents__c</fullName>
    <description>Number of safety incidents</description>
    <inlineHelpText>Number of safety incidents</inlineHelpText>
    <label>Safety Incidents</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/main/domain/Missions.cls
public class Missions extends fflib_SObjects implements IMissions {
  private Database.BatchableContext THEBATCHABLECONTEXT;
  public static IMissions newInstance(List<Mission__c> recordList) {
    return (IMissions) Application.Domain.newInstance(recordList);
  }

  public static IMissions newInstance(Set<Id> recordIdSet) {
    return (IMissions) Application.Domain.newInstance(recordIdSet);
  }

  public Missions(List<Mission__c> sObjectList) {
    super(sObjectList, Schema.Mission__c.SObjectType);
  }

  public List<Mission__c> getMissions() {
    return (List<Mission__c>) getRecords();
  }

  public Map<ID, Mission__c> getMissionsMap() {
    return new Map<ID, Mission__c>(getMissions());
  }

  public void setBatchableContext(
    Database.BatchableContext theBatchableContext
  ) {
    this.THEBATCHABLECONTEXT = theBatchableContext;
  }

  public void updatePilotRatings(fflib_ISObjectUnitOfWork theUnitOfWork) {
    for (Mission__c thisMission : getMissions()) {
      try {
        Double weightedCompletionRate = 0.3 * thisMission.Completion_Rating__c;
        Double weightedSafetyIncidents = -0.5 * thisMission.Safety_Incidents__c;

        Double newOverallRating =
          thisMission.Pilot__r.Pilot_Rating__c + thisMission.Overall_Rating__c;
        thisMission.Pilot__r.Pilot_Rating__c = newOverallRating;
        theUnitOfWork.registerDirty(thisMission.Pilot__r);
      } catch (Exception exe) {
        Error_Log__c thisErrorLog = new Error_Log__c(
          Name = 'PilotRatingBatch' + THEBATCHABLECONTEXT.getJobId(),
          Async_Apex_Job_Id__c = THEBATCHABLECONTEXT.getJobId(),
          Message__c = 'Errorr Running Batch PilotRatingBatch',
          Stacktrace__c = String.valueOf(exe)
        );
        theUnitOfWork.registerNew(thisErrorLog);
      }
    }
  }

  public class Constructor implements fflib_IDomainConstructor {
    public fflib_SObjects construct(List<Object> objectList) {
      return new Missions((List<SObject>) objectList);
    }
  }
}