force-app/main/default/objects/Equipment_Maintenance_Item__c/Equipment_Maintenance_Item__c.object-meta.xml
<CustomObject>
    <label>Equipment Maintenance Item</label>
    <nameField>
        <displayFormat>PART-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Maintenance Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Maintenance_Item__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No spare parts meet this description or name.</errorMessage>
        <filterItems>
            <field>Product2.Replacement_Part__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Equipment Maintenance Items</relationshipLabel>
    <relationshipName>Equipment_Maintenance_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment_Maintenance_Item__c/fields/Maintenance_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Cycle__c</fullName>
    <formula>Equipment__r.Maintenance_Cycle__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Maintenance Cycle (Days)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment_Maintenance_Item__c/fields/Maintenance_Request__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Request__c</fullName>
    <label>Maintenance Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipment Maintenance Items</relationshipLabel>
    <relationshipName>Equipment_Maintenance_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipment_Maintenance_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/main/selector/EquipmentMaintenanceItemsSelector.cls
public class EquipmentMaintenanceItemsSelector extends fflib_SObjectSelector implements IEquipmentMaintenanceItemsSelector {
  public static IEquipmentMaintenanceItemsSelector newInstance() {
    return (IEquipmentMaintenanceItemsSelector) Application.Selector.newInstance(
      Equipment_Maintenance_Item__c.SObjectType
    );
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Equipment_Maintenance_Item__c.Id,
      Equipment_Maintenance_Item__c.Equipment__c,
      Equipment_Maintenance_Item__c.Maintenance_Request__c,
      Equipment_Maintenance_Item__c.Name,
      Equipment_Maintenance_Item__c.Quantity__c,
      Equipment_Maintenance_Item__c.Maintenance_Cycle__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Equipment_Maintenance_Item__c.SObjectType;
  }

  public List<Equipment_Maintenance_Item__c> selectAll() {
    return (List<Equipment_Maintenance_Item__c>) Database.query(
      newQueryFactory().toSOQL()
    );
  }

  public List<Equipment_Maintenance_Item__c> selectByMaintenanceRequest(
    Set<ID> caseIDSet
  ) {
    return (List<Equipment_Maintenance_Item__c>) Database.query(
      newQueryFactory()
        .setCondition('Maintenance_Request__c in: caseIDSet')
        .toSOQL()
    );
  }
}