force-app/main/default/objects/Order_Event__e/Order_Event__e.object-meta.xml
<CustomObject>
    <label>Order Event</label>
    <pluralLabel>Order Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Order_Event__e/fields/Has_Shipped__c.field-meta.xml
<CustomField>
    <fullName>Has_Shipped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Shipped</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/main/domain/OrderEvents.cls
public class OrderEvents extends fflib_SObjects implements IOrderEvents {
  public static IOrderEvents newInstance(List<Order_Event__e> recordList) {
    return (IOrderEvents) Application.Domain.newInstance(recordList);
  }

  public static IOrderEvents newInstance(Set<Id> recordIdSet) {
    return (IOrderEvents) Application.Domain.newInstance(recordIdSet);
  }

  public OrderEvents(List<Order_Event__e> sObjectList) {
    super(sObjectList, Schema.Order_Event__e.SObjectType);
  }

  public List<Order_Event__e> getOrderEvents() {
    return (List<Order_Event__e>) getRecords();
  }

  public Map<ID, Order_Event__e> getOrderEventsMap() {
    return new Map<ID, Order_Event__e>(getOrderEvents());
  }

  public void processOrderEvents(fflib_ISObjectUnitOfWork theUnitOfWork) {
    for (Order_Event__e orderEvent : getOrderEvents()) {
      if (orderEvent.Has_Shipped__c == true) {
        Task thisTask = new Task();
        thisTask.Priority = 'Medium';
        thisTask.Subject = 'Follow up on shipped order 105';
        thisTask.OwnerId = orderEvent.CreatedById;
        theUnitOfWork.registerNew(thisTask);
      }
    }
  }

  public class Constructor implements fflib_IDomainConstructor {
    public fflib_SObjects construct(List<Object> objectList) {
      return new OrderEvents((List<SObject>) objectList);
    }
  }
}