force-app/main/default/objects/Order_Event__e/Order_Event__e.object-meta.xml
<CustomObject>
    <label>Order Event</label>
    <pluralLabel>Order Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Order_Event__e/fields/Has_Shipped__c.field-meta.xml
<CustomField>
    <fullName>Has_Shipped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Shipped</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/main/triggerhandler/OrderEventTriggerHandler.cls
public class OrderEventTriggerHandler extends fflib_SObjectDomain {
  static fflib_ISObjectUnitOfWork theUnitOfWork = Application.UnitOfWork.newInstance();
  public OrderEventTriggerHandler(List<SObject> sObjectList) {
    super(sObjectList);
  }

  // Method to handle after insert event
  //If the order has shipped (event.Has_Shipped__c == true), create a task with the following values:
  //Priority: 'Medium'
  //Subject: 'Follow up on shipped order 105'
  //OwnerId: event.CreatedById
  //Note: You are assigning the task OwnerId to the same user who published the event. This step keeps things simple so you don't have to perform any prerequisites.
  public override void handleAfterInsert() {
    System.debug('Hello World');
    IOrderEvents theseOrderEvents = OrderEvents.newInstance(
      (List<Order_Event__e>) Records
    );
    theseOrderEvents.processOrderEvents(theUnitOfWork);
    theUnitOfWork.commitWork();
  }
}